/**
 * Renders a niche research report to a multi-page Letter PDF.
 */

import { escapeHtml } from "../html/escape";
import { renderPdfFromCss } from "../pdf";
import { BAND_COLORS } from "./score";
import { BOOK_TYPE_LABELS } from "./types";
import type { NicheReport } from "./types";

const esc = escapeHtml;

function ideaCard(idea: NicheReport["ideas"][number], rank: number): string {
  const c = BAND_COLORS[idea.band];
  const types = idea.bookTypes.map((t) => BOOK_TYPE_LABELS[t] ?? t).join(", ");
  const f = idea.factors;
  const stat = (label: string, v: number) =>
    `<td><div class="stat-l">${label}</div><div class="stat-v">${v}</div></td>`;

  return `
    <div class="card">
      <div class="card-head">
        <div class="rank">${rank}</div>
        <div class="niche">${esc(idea.niche)}</div>
        <div class="score" style="background:${c.bg};color:${c.fg}">
          ${esc(idea.opportunity)} · ${esc(idea.band)}
        </div>
      </div>
      <table class="stats">
        <tr>
          ${stat("Demand", f.demand)}
          ${stat("Competition", f.competition)}
          ${stat("Evergreen", f.evergreen)}
          ${stat("Monetization", f.monetization)}
        </tr>
      </table>
      <div class="rec"><b>Recommended:</b> ${esc(BOOK_TYPE_LABELS[idea.recommendedBookType] ?? idea.recommendedBookType)}
        <span class="muted">&nbsp;(also: ${esc(types)})</span></div>
      <div class="notes"><b>Seasonal:</b> ${esc(idea.seasonal)}</div>
      <div class="notes"><b>Monetization:</b> ${esc(idea.monetizationNote)}</div>
    </div>`;
}

export async function renderNicheReportPdf(report: NicheReport): Promise<Uint8Array> {
  const meta = [
    report.audience && `Audience: ${report.audience}`,
    report.category && `Category: ${report.category}`,
    report.country && `Market: ${report.country}`,
  ]
    .filter(Boolean)
    .map((s) => esc(s as string))
    .join(" &nbsp;·&nbsp; ");

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"/>
<style>
  @page { size: 8.5in 11in; margin: 0.6in; }
  * { box-sizing: border-box; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  body { margin: 0; font-family: Arial, Helvetica, sans-serif; color: #111; font-size: 10pt; }
  h1 { font-size: 20pt; margin: 0 0 2pt; }
  .sub { color: #555; font-size: 9pt; }
  .meta { color: #444; font-size: 9pt; margin-top: 4pt; }
  .rule { border-top: 2px solid #111; margin: 8pt 0 12pt; }
  .card { border: 1px solid #ddd; border-radius: 6px; padding: 8pt 10pt; margin-bottom: 8pt; break-inside: avoid; }
  .card-head { display: flex; align-items: center; gap: 8pt; }
  .rank { width: 20pt; height: 20pt; background: #111; color: #fff; border-radius: 50%; text-align: center; line-height: 20pt; font-size: 9pt; font-weight: bold; }
  .niche { flex: 1; font-size: 12pt; font-weight: bold; }
  .score { font-size: 9pt; font-weight: bold; padding: 2pt 8pt; border-radius: 999px; white-space: nowrap; }
  .stats { width: 100%; margin: 6pt 0; border-collapse: collapse; }
  .stats td { text-align: center; border: 1px solid #eee; padding: 3pt; width: 25%; }
  .stat-l { color: #777; font-size: 7.5pt; text-transform: uppercase; letter-spacing: 0.03em; }
  .stat-v { font-size: 12pt; font-weight: bold; }
  .rec { font-size: 9.5pt; margin-top: 2pt; }
  .notes { font-size: 9pt; color: #333; margin-top: 2pt; }
  .muted { color: #888; }
  .footer { color: #999; font-size: 8pt; margin-top: 6pt; }
</style></head><body>
  <h1>Niche Research: ${esc(report.keyword)}</h1>
  <div class="sub">${report.ideas.length} opportunities, ranked by opportunity score · ${new Date(report.created_at).toLocaleDateString()}</div>
  ${meta ? `<div class="meta">${meta}</div>` : ""}
  <div class="rule"></div>
  ${report.ideas.map((idea, i) => ideaCard(idea, i + 1)).join("")}
  <div class="footer">Generated by KDP Mafia · Estimates are AI-generated guidance, not guarantees.</div>
</body></html>`;

  return renderPdfFromCss(html);
}
